Ch register drivers and operators cp-36
atlp-rwanda/phantom-fe-codebandits pull request #17
Opened 2022-02-23 08:01 UTC by Abdulkeza

# What does this PR do?
- [x] Register operators and Drivers

# Description of Task to be completed?
- [x] Register driver
- [x] Register Operator

# How should this be manually tested?
[Clone](https://github.com/atlp-rwanda/phantom-fe-codebandits.git)
-npm i
-npm start

# Any background context you want to provide?
(N/A)
# What are the relevant pivotal tracker stories?
[or0BODOS](https://trello.com/c/or0BODOS/36-register-drivers-operators)

# Questions:
N/A

2022-03-01 08:19 UTC, samuel-shyaka-dus requested changes
This is great work Fab, Here below is some feedback

2022-03-01 08:19 UTC, samuel-shyaka-dus commented on src/forms/FormComponent.js
> +  return (
Put some margin on the right side of the form

2022-03-01 08:19 UTC, samuel-shyaka-dus commented on src/pages/__test__/RegisterForm.test.js
> +import { shallow } from 'enzyme';
I think it would be better if you created a test folder in the forms folder and then put this file there

2022-03-01 08:19 UTC, samuel-shyaka-dus commented on src/forms/FormInputs.js
> +      placeholder: 'Hategekimana'
Change the placeholder to a first name

2022-03-01 08:19 UTC, samuel-shyaka-dus commented on src/forms/FormInputs.js
> +      placeholder: 'Venuste'
Change the placeholder to a last name

2022-03-02 06:42 UTC, feyton commented on src/forms/FormInputs.js
> +      placeholder: 'Hategekimana'
Fixed

2022-03-07 20:07 UTC, closed without merging