# CP-9 landing page fixes
atlp-rwanda/phantom-fe-codebandits pull request #19
Opened 2022-02-27 14:48 UTC by samuel-shyaka-dus

#### What the PR does
Fix bugs of the landing page

#### Description of Tasks to be completed

- [ ] Responsiveness is improved
- [ ] Users should see different states for interactive elements
- [ ] Skeleton UIs/screen are/is shown when the page loads/is loading
- [ ] All tests are written

#### How this should be manually tested
Clone the project repository linked [here](https://github.com/atlp-rwanda/phantom-fe-codebandits)

```
cd phantom-fe-codebandits/
git checkout bg-landing-page-fixes-cp-9
git pull origin bg-landing-page-fixes-cp-9
npm install
npm run start
run http://localhost:3000 in your browser
```

#### Relevant Trello Card
[#CP-9](https://trello.com/c/X1Wfyki5/9-landing-page-fixes)

2022-03-02 19:10 UTC, Jkadhuwa requested changes
Nice work on the tests, find some comments below, and also on mobile view increase the card to accommodate the languages when the button is clicked.

2022-03-02 19:10 UTC, Jkadhuwa commented on src/components/__test__/Button.test.js
>  import React from 'react';
Rename the test folder to __tests__ for them to be ignored by codeclimate

2022-03-02 19:10 UTC, Jkadhuwa commented on src/components/LanguageDropdown.js
> -    <ul className=" z-10">
Use select tag in place of the list

2022-03-03 05:22 UTC, Jkadhuwa submitted a review, later dismissed

2022-03-03 09:51 UTC, Yvad60 reviewed
Great job man! the only thing I noticed is that the buttons on the header are a little bigger, it looks fine on the landing page but since the header will be used will be used on other pages they can appear appear to be bigger than the rest of page content 
also that the same with the skeleton UI they look bigger and too gray considering the background color of the page

2022-03-03 10:07 UTC, Abdulkeza reviewed
First of All, you did a great Job, Sam, so one thing, just if you take a look at Mobile Version (320px), the contents are breaking down, if you can , just you can add responsive for that

2022-03-03 15:17 UTC, samuel-shyaka-dus commented
> First of All, you did a great Job, Sam, so one thing, just if you take a look at Mobile Version (320px), the contents are breaking down, if you can , just you can add responsive for that

Thanks, Abdul,
I think 375px is the minimum of normal mobile devices

2022-03-03 15:18 UTC, samuel-shyaka-dus commented
> Great job man! the only thing I noticed is that the buttons on the header are a little bigger, it looks fine on the landing page but since the header will be used on other pages those buttons can appear to be bigger than the rest of page content also that the same with the skeleton UI they look bigger and too gray considering the background color of the page

Let me decrease them a little bit

2022-03-03 16:48 UTC, Jkadhuwa approved these changes

2022-03-03 16:48 UTC, merged