fix main card display
atlp-rwanda/phantom-fe-codebandits pull request #20
Opened 2022-02-28 06:42 UTC by Yvad60

2022-03-01 08:34 UTC, samuel-shyaka-dus requested changes
This is great work Yvad, 
On the medium and smaller screens, try to make the top part of the image behind the card a little more visible

2022-03-02 06:34 UTC, feyton submitted a review, later dismissed
Great work @Yvad60 the responsiveness and test coverage has been improved.

2022-03-03 09:08 UTC, samuel-shyaka-dus requested changes
On larger screens, try to center the image on y-axis. 
on smaller screens make the image, a little bit more visible at the top.

2022-03-03 12:21 UTC, Yvad60 commented
> On larger screens, try to center the image on y-axis. on smaller screens make the image, a little bit more visible at the top.

yeah!

2022-03-03 14:41 UTC, Abdulkeza commented on src/pages/Login.js
>  import busMapImg from '../assets/busMap.png';
Try to add space between built-in modules and your own module

2022-03-03 14:41 UTC, Abdulkeza commented on src/pages/__test__/Login.test.js
> +describe('Landing page functionality tests', () => {
Are you testing a landing page??

2022-03-07 12:10 UTC, samuel-shyaka-dus approved these changes

2022-03-07 15:47 UTC, merged