setup drivers management page
atlp-rwanda/phantom-fe-codebandits pull request #22
Opened 2022-03-02 03:28 UTC by Yvad60

#### What the PR does
allows the admin to create the role and set its permissions, so that different users can only access & perform data/operations to which they are authorized.

#### Description of Tasks to be completed

- [ ] The Administrator should be able to create, update, and delete roles.
- [ ] The administrator should be able to set and update the role's permissions.
- [ ] Appropriate error messages are displayed on unsuccessful attempts
- [ ] Skeleton UIs/screen are/is shown when the page loads/is loading.
- [ ] Created pages are responsive.

#### How this should be manually tested
Clone the project repository linked [here](https://github.com/atlp-rwanda/phantom-fe-codebandits)

```
cd phantom-fe-codebandits/
git checkout ft-create-roles-set-permissions-cp-32
git pull 
npm install
npm run start
run http://localhost:3000 in your browser
```

#### Relevant Trello Card
[#CP-32](https://trello.com/c/3bd3Q7a2/32-create-roles-set-permissions)

2022-03-14 13:29 UTC, samuel-shyaka-dus requested changes
This is great work. Find a better way to make the table responsive. For  example for smaller screens, you can display only a few columns per page then create a column title, name it **more** and make it a dropdown. once a user clicks on **more** they can choose a title form the dropdown (for example: Assigned bus) and the column will contain the data that correspond to the title.

2022-03-16 11:10 UTC, Abdulkeza approved these changes, later dismissed
Great work! and I've seen that the issues that we saw were all solved.

2022-03-16 11:18 UTC, samuel-shyaka-dus approved these changes, later dismissed

2022-03-16 16:24 UTC, Jkadhuwa requested changes
Nice work @feyton and @Yvad60 , left some comments below. Please make sure you remove all unnecessary console logs and fix your snapshot test.

2022-03-16 16:24 UTC, Jkadhuwa commented on src/Modals/ChangeRole.js
> +    console.log(role);
remove consoles.

2022-03-16 16:24 UTC, Jkadhuwa commented on src/pages/dashboard/RolesPage.js
> +                <li>Object</li>
Think of  a better name here

2022-03-16 16:24 UTC, Jkadhuwa commented on src/Modals/ChangeRole.js
> +        <PrimaryButton type={'submit'} name={'Continue'} />
After changing role and clicking on the "Continue" button nothing happens after the toast

2022-03-16 16:24 UTC, Jkadhuwa commented on src/Modals/ChangeRole.js
> +            <b>Name</b>: {name}
Increase the size of the card, its so congested.

2022-03-16 16:52 UTC, feyton commented on src/pages/dashboard/RolesPage.js
> +                <li>Object</li>
I guess using Model would be better 
What do you think

2022-03-24 14:51 UTC, samuel-shyaka-dus approved these changes

2022-03-24 14:58 UTC, Abdulkeza approved these changes
Great job Fab!!

2022-03-24 15:02 UTC, Jkadhuwa approved these changes

2022-03-24 15:03 UTC, merged