#CP-37 Simulate the bus motion
atlp-rwanda/phantom-fe-codebandits pull request #25
Opened 2022-03-08 18:44 UTC by samuel-shyaka-dus

#### What the PR does
Allows the driver to be able to command the bus to start, stop, speed up, and slow down the bus so that the bus can move.

#### Description of Tasks to be completed

- [ ] The driver should be able to command the bus to start, move and stop.
- [ ] The driver should be able to update the bus info on bus stops (those that alighted and left).
- [ ] The driver should be able to command the bus to speed up and slow down..
- [ ] The **users** should be able to view the bus movement in real-time.
- [ ] The page is responsive
- [ ] Skeleton UIs/screen are/is shown when the page loads/is loading.
- [ ] Appropriate error messages are displayed on unsuccessful attempts.

#### How this should be manually tested
Clone the project repository linked [here](https://github.com/atlp-rwanda/phantom-fe-codebandits)

```
cd phantom-fe-codebandits/
git checkout ft-simulate-the-bus-motion-cp-37
git pull origin ft-simulate-the-bus-motion-cp-37
npm install
npm run start
run http://localhost:3000 in your browser
```

#### Relevant Trello Card
[#CP-37](https://trello.com/c/BxUjbRV8/37-simulate-the-bus-motion)

2022-03-20 18:00 UTC, feyton requested changes
### Great work
@samuel-shyaka-dus this is really great and the tracking is fantastic. The implementation is very credible, 
### Suggestions
Using a custom message to explain to the use why we need their location
Ex: **"We use your location to help you plan your trip accordingly"**. Choose allow on the next pop up.
`Its not possible to customize the browser pop, but the pre-request message would be great`

### Requested
Check the individual comments I left especially on the public profile.

2022-03-20 18:00 UTC, feyton commented on src/pages/profiles/PublicProfile.js
> +                </h2>
This file expose too **much information** and could use a redesign with sensitive information removed.

### Example
Instead of using the form we can create a specific page. 
Take inspiration from here and we can improve on it

![image](https://user-images.githubusercontent.com/28519395/159175793-cdd07faa-2281-4394-b9cb-cfc1f18ffd97.png)

2022-03-20 18:00 UTC, feyton commented on src/useLoader.js
> +    }, 500);
This timing is really credible.

2022-03-20 18:00 UTC, feyton commented on src/utils/GetInstructions.js
> +import L from 'leaflet';
This file is no longer useful as the feature is not implemented on the page. The purpose of it was to generate information to the drive throughout the route.

2022-03-21 06:09 UTC, samuel-shyaka-dus commented on src/pages/profiles/PublicProfile.js
> +                </h2>
This is a great idea

2022-03-21 06:11 UTC, samuel-shyaka-dus commented
> ### Great work
> @samuel-shyaka-dus this is really great and the tracking is fantastic. The implementation is very credible,
> 
> ### Suggestions
> Using a custom message to explain to the use why we need their location Ex: **"We use your location to help you plan your trip accordingly"**. Choose allow on the next pop up. `Its not possible to customize the browser pop, but the pre-request message would be great`
> 
> ### Requested
> Check the individual comments I left especially on the public profile.

Thank you for the suggestions, Fab. I will try to implement them.

2022-03-23 19:00 UTC, Yvad60 requested changes
Nice work with testing and improvement on designs they look much cleaner, what i noticed to to improve is about on what should happen when someone chooses  another route while he was tracking another one.
so far when you change the route will be changed but the bus icon is moving back and forth along the old route

2022-03-24 09:26 UTC, Yvad60 approved these changes

2022-03-24 09:27 UTC, Abdulkeza approved these changes
U did a great job mr Sam

2022-03-24 09:54 UTC, feyton approved these changes
@samuel-shyaka-dus 
### Overview
This is really great work. And the public profile is really good now

### Fixed changes
The requested changes are worked on including the public profile that show minimal user information to the public.

2022-03-24 10:08 UTC, Jkadhuwa approved these changes

2022-03-24 10:10 UTC, merged