feat (languages)- Support multiple language
atlp-rwanda/phantom-fe-codebandits pull request #37
Opened 2022-04-04 20:26 UTC by feyton

- The project is set to use multiple language
- The selected language is being sent on each request

[Finishes #CP-4]

2022-04-24 09:52 UTC, samuel-shyaka-dus approved these changes, later dismissed
Nice work @feyton, this is very useful because it will allow us to make translations for multiple features of this application and thus we will be able to increase it's accessibility.

2022-04-25 06:10 UTC, Yvad60 approved these changes, later dismissed
Nice work @feyton with the translations on the front end. I have noticed that in some cases translations in other languages break page designs maybe because of words length maybe we will try to find a work around that.  for now this PR is ready for merge

2022-04-25 17:03 UTC, Jkadhuwa requested changes, later dismissed
Good work, left some comment for you to attend to.

2022-04-25 17:03 UTC, Jkadhuwa commented on src/pages/LandingPage.js
> +            <Card
We can create a data object and loop it through the card component with the data. that will solve the codeclimate issue

2022-04-25 19:00 UTC, samuel-shyaka-dus approved these changes

2022-04-25 19:10 UTC, Jkadhuwa approved these changes

2022-04-25 19:10 UTC, merged