#CP-21 feat: reset password
atlp-rwanda/phantom-fe-codebandits pull request #38
Opened 2022-04-20 06:56 UTC by Abdulkeza

## What does this PR do?
- Reset the password for the users
## Description of Task to be completed?

- [ ] The user should be able to provide their email.
- [ ] The driver or operator should be able to log in with the new password.
- [ ] The driver or operator should be able to receive a reset password link in their email.
- [ ] The driver or operator should be able to reset the password( i.e. provide a new password).
- [ ] All Requests should be sent to the backend and return appropriate responses
- [ ] The system should work with real data from the database

## How should this be manually tested?
- [Clone](https://github.com/atlp-rwanda/phantom-fe-codebandits.git)
- git co ft-reset-password-cp-21
- npm i
- npm t
 
## Any background context you want to provide?
(N/A)

## What are the relevant pivotal tracker stories?
[SUz0qwab](https://trello.com/c/SUz0qwab/21-reset-password)

## Screenshots (if appropriate)

2022-04-27 07:02 UTC, samuel-shyaka-dus requested changes
This is great work @Yvad60, here below is some feedback.

2022-04-27 07:02 UTC, samuel-shyaka-dus commented on src/pages/accounts/NewPasswordForm.js
> +                  Invalid Token
I think we can change this message to something else that the user can understand. The user may not understand what the token is.

2022-04-27 08:22 UTC, feyton approved these changes, later dismissed
### Approval
This is really great work @Abdulkeza and @Yvad60 
Try to fix the issue with codeclimate but since the feature is well integrated.

2022-04-28 16:04 UTC, samuel-shyaka-dus approved these changes

2022-04-28 16:13 UTC, feyton approved these changes
### Approval
This really great work @team

2022-04-28 16:37 UTC, merged