#CP-26 Setup Redux
atlp-rwanda/phantom-fe-codebandits pull request #4
Opened 2022-02-09 15:28 UTC by samuel-shyaka-dus

#### What the PR does
Configure the app to use Redux as a state management library

#### Description of Tasks to be completed

- Set up Redux 
- Create a simple number counter on the landing page using redux as the state management library

#### How this should be manually tested
Clone the project repository linked [here](https://github.com/atlp-rwanda/phantom-fe-codebandits)

```
cd phantom-fe-codebandits/
git checkout ch-setup-redux-cp-26
git fetch origin
npm install
npm run start
run http://localhost:3000 in your browser
```

#### Relevant Trello Card
[#CP-26](https://trello.com/c/94jYzQr3/26-setup-redux)

2022-02-09 17:02 UTC, Abdulkeza submitted a review, later dismissed
Hey! on my side app is working well, and Redux too
 you did a great job.

2022-02-09 17:13 UTC, Yvad60 submitted a review, later dismissed
everything including the counter is working as expected!

2022-02-10 05:14 UTC, Jkadhuwa requested changes
Nice work so far, attend to the feedback left below.

2022-02-10 05:14 UTC, Jkadhuwa commented on src/index.js
> +const store = configureStore({
Move the store configuration into its own file inside the redux folder

2022-02-10 05:14 UTC, Jkadhuwa commented on src/App.js
> +    console.log(counter)
You can remove the log

2022-02-10 05:14 UTC, Jkadhuwa commented on src/App.js
> +    const counter = useSelector((state) => state?.counter);
You can destructure value from state.counter directly (es6)

2022-02-10 10:47 UTC, Jkadhuwa approved these changes

2022-02-10 10:49 UTC, merged