#CP-29 feat: CRUD operations for routes
atlp-rwanda/phantom-fe-codebandits pull request #45
Opened 2022-04-27 06:20 UTC by Yvad60

#### What does this PR do?
It enables an operator to create routes so that buses can travel in pre-defined routes. and so that users can view pre-defined routes.

#### Description of the tasks to be completed
- [x] The operator should be able to create, update, and delete a bus.
- [x] The operator should be able to view a paginated list of routes in the system.
- [x] Users should be able to view the bus's details.
- [x] All Requests should be sent to the backend and return appropriate responses
- [x] Appropriate error messages are displayed on unsuccessful attempts
- [x] The system should work with real data from the database

#### How should this be manually tested?

```
N/A
```

#### Pre-requisites:

N/A

#### What are the relevant trello story:
[#CP-29](https://trello.com/c/lry7W7lP/29-crud-operations-for-routes)

2022-05-01 13:06 UTC, samuel-shyaka-dus requested changes
Nice work @Abdulkeza. When trying to edit the route, it only works when you change both the origin and the destination. When you try to change only one of the two, it throws an error that the other one is null. You can look into that.

2022-05-01 13:07 UTC, samuel-shyaka-dus requested changes
[REDACTED]

2022-05-05 20:04 UTC, samuel-shyaka-dus submitted a review, later dismissed

2022-05-05 20:34 UTC, Abdulkeza approved these changes, later dismissed

2022-05-05 20:53 UTC, samuel-shyaka-dus approved these changes

2022-05-05 20:54 UTC, merged