feat(integration): crud operations for buses
atlp-rwanda/phantom-fe-codebandits pull request #47
Opened 2022-04-28 21:32 UTC by Yvad60

#### What does this PR do?
allows the operator/admin to be able to register edit and delete buses using real data from the backend

#### Description of the tasks to be completed
- [x] The operator should be able to create, update, and delete a bus.
- [x] The operator should be able to view a paginated list of buses in the system.
- [x] Users should be able to view the bus's details.
- [x] All Requests should be sent to the backend and return appropriate responses
- [x] Appropriate error messages are displayed on unsuccessful attempts
- [x] The system should work with real data from the database

#### How should this be manually tested?

```
git fetch
git checkout ft-crud-operations-for-buses-cp-28
npm install
npm start 
login as an admin to be able to access buses
test bus cruds functionality
```

#### Pre-requisites:

- Clone the project

#### What are the relevant trello story:
[#CP-28](https://trello.com/c/0JmHZliU/28-crud-operations-for-buses)

2022-05-01 15:42 UTC, samuel-shyaka-dus reviewed
Nice work @Yvad60, The code base looks good and the feature is working as expected. After you finish working on the tests, I believe the PR will be ready to be merged.

2022-05-04 06:24 UTC, feyton approved these changes, later dismissed
### Approval
@Yvad60 this is great work, I am approving your work as the feature is well implemented and works as expected.

2022-05-04 10:34 UTC, Jkadhuwa requested changes
Good work, solve codeclimate issues and increase coverage and it will be good for merging.
Refer here to test Axios requests.
https://betterprogramming.pub/testing-react-list-using-axios-and-react-testing-library-d000eebf3413

2022-05-04 10:34 UTC, Jkadhuwa commented on src/components/dropdowns/BusManagement.js
> +    const results = await Swal.fire({
You can create a custom hook to handle all the delete method and call it inside the handleDelete(); see implementation below.

https://reactjs.org/docs/hooks-custom.html

2022-05-04 10:34 UTC, Jkadhuwa commented on src/components/forms/Buses.js
> +      if (validationErrors) {
Avoid nesting  of conditional operators and also you can move this to a custom hook to increase readability and reduce complexity

2022-05-10 11:49 UTC, closed without merging

2022-05-10 11:50 UTC, feyton commented
This PR has been implemented on another branch